// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"QTE_LakeMaster","status":true,"description":"QTE Plugin - Reflex sequence with anticipation delay, configurable input phase - v1.8","parameters":{"Success Switch ID":"10","QTE Window X":"200","QTE Window Y":"200","Prep Phase Duration":"150","Input Duration":"60","Delta between wrong input":"120"}},
{"name":"CaptureVideoPlayer","status":true,"description":"Lecture vidéo personnalisée après délai - CaptureMaster - v1.0","parameters":{}},
{"name":"ZQSDMapper","status":true,"description":"Active les touches ZQSD pour le déplacement du joueur (support AZERTY) [Hunter x Hunter Game].","parameters":{}},
{"name":"ShowSign","status":true,"description":"Affiche un panneau directionnel sous forme de fenêtre de type dialogue semi-transparente et bloque le mouvement jusqu'à validation. [Hunter x Hunter Game]","parameters":{}},
{"name":"ATB_Hunter_Core","status":true,"description":"[HUNTERxATB] Plugin central ATB en fichiers séparés - v1.0","parameters":{}},
{"name":"FogScreen","status":true,"description":"Affiche un fog configurable par carte via image et défilement (RPG Maker MV) — façon XP amélioré ✨","parameters":{}}
];
